language: go

os:
  - linux
  - osx

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  # from go 1.8.7, 1.9.4, 1.10rc2 there is a restriction on CGO see https://github.com/bugst/go-serial/issues/50
  # this restriction has some consequences on darwin build
  - 1.8.6
  - 1.9.3

go_import_path: go.bug.st/serial.v1

env:
  - TEST_OS=linux TEST_ARCH=386
  - TEST_OS=linux TEST_ARCH=amd64
  - TEST_OS=linux TEST_ARCH=arm
  - TEST_OS=windows TEST_ARCH=386
  - TEST_OS=windows TEST_ARCH=amd64
  - TEST_OS=darwin TEST_ARCH=386
  - TEST_OS=darwin TEST_ARCH=amd64
  - TEST_OS=freebsd TEST_ARCH=amd64
  - TEST_OS=openbsd TEST_ARCH=amd64
  - TEST_OS=openbsd TEST_ARCH=386
  - TEST_OS=openbsd TEST_ARCH=arm

matrix:
  exclude:
  - os: linux # no point in testing go1.8.6 on Linux
    go: 1.8.6
  - os: linux # no point in testing go1.9.3 on Linux
    go: 1.9.3
  - os: osx   # go1.8.x after 1.8.6 is not supported on OSX
    go: 1.8.x
  - os: osx   # go1.9.x after 1.9.3 is not supported on OSX
    go: 1.9.x
  - os: linux
    env: TEST_OS=darwin TEST_ARCH=386
  - os: linux
    env: TEST_OS=darwin TEST_ARCH=amd64
  - os: osx
    env: TEST_OS=linux TEST_ARCH=386
  - os: osx
    env: TEST_OS=linux TEST_ARCH=amd64
  - os: osx
    env: TEST_OS=linux TEST_ARCH=arm
  - os: osx
    env: TEST_OS=windows TEST_ARCH=386
  - os: osx
    env: TEST_OS=windows TEST_ARCH=amd64
  - os: osx
    env: TEST_OS=freebsd TEST_ARCH=amd64
  - os: osx
    env: TEST_OS=openbsd TEST_ARCH=amd64
  - os: osx
    env: TEST_OS=openbsd TEST_ARCH=386
  - os: osx
    env: TEST_OS=openbsd TEST_ARCH=arm
  allow_failures:
    - env: TEST_OS=openbsd TEST_ARCH=arm

before_install:

script:
  - GOARM=5 GO386=387 GOOS=$TEST_OS GOARCH=$TEST_ARCH go get github.com/stretchr/testify/require
  - GOARM=5 GO386=387 GOOS=$TEST_OS GOARCH=$TEST_ARCH go get golang.org/x/sys/windows
  - GOARM=5 GO386=387 GOOS=$TEST_OS GOARCH=$TEST_ARCH go build -v go.bug.st/serial.v1
  - GOARM=5 GO386=387 GOOS=$TEST_OS GOARCH=$TEST_ARCH go test -c -v go.bug.st/serial.v1

notifications:
  email:
    recipients:
      - c.maglie@bug.st
    on_success: change
    on_failure: always

